// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAvailableNodeVersions() {
  return window['go']['main']['App']['GetAvailableNodeVersions']();
}

export function GetInstalledNodeVersions() {
  return window['go']['main']['App']['GetInstalledNodeVersions']();
}

export function InstallNodeVersion(arg1) {
  return window['go']['main']['App']['InstallNodeVersion'](arg1);
}

export function SwitchNodeVersion(arg1) {
  return window['go']['main']['App']['SwitchNodeVersion'](arg1);
}

export function UninstallNodeVersion(arg1) {
  return window['go']['main']['App']['UninstallNodeVersion'](arg1);
}
