name: Build and Release Wails App

on:
  push:
    tags:
      - 'v*.*.*'  # 当推送新标签时触发工作流，这通常对应创建新的 release

jobs:
  build:
    name: Build for Windows
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go environment
        uses: actions/setup-go@v3
        with:
          go-version: 1.22  # 根据项目所需的 Go 版本

      - name: Install Wails CLI
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Install dependencies
        run: go mod tidy

      - name: Build Windows executable
        run: wails build -platform windows/amd64

      - name: List build directory
        run: dir D:\a\node-version-switcher\node-version-switcher\build\bin

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: wails-windows-exe
          path: D:\a\node-version-switcher\node-version-switcher\build\bin\node-version-switcher.exe

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: wails-windows-exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: wails-windows-exe/node-version-switcher.exe  # 从下载的 Artifact 位置获取文件
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
